stjude-rust-labs/sprocket

- Cargo.toml
- README.md
- src/commands.rs
- src/commands/explain.rs
- src/main.rs
- src/report.rs
All the functionality changes here are quite straightforward. I added a new dependency, `colored`, in order to get some "prettier" explain output. Maybe there's more we can do in that direction?
> feat: explain command

- README.md
- docs/.gitignore
- docs/.vitepress/config.mts
- docs/.vitepress/theme/Layout.vue
- docs/.vitepress/theme/index.ts
- docs/.vitepress/theme/style.css
- docs/index.md
- docs/installation.md
- docs/overview.md
- docs/package-lock.json
- docs/package.json
- docs/vscode/getting-started.md
I wanted to add a few sentences describing the philosophy and goals that led to the creation of Sprocket. Though everything on the page may not be true (yet) today, it will be a good goal-post to work towards while providing the community some sense of where we are going.
> docs: adds the initial documentation site

- CHANGELOG.md
- src/commands/check.rs
This commit delays showing the progress bar until two seconds of analysis have passed.
For small analysis jobs, like single files, this will prevent a progress bar from showing and then immediately completing.
> fix: delay showing the progress bar.

- .github/workflows/release.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/commands.rs
- src/commands/analyzer.rs
- src/commands/check.rs
- src/commands/explain.rs
- src/commands/format.rs
- src/main.rs
This commit adds the `format` command to `sprocket`.
The command will format a single WDL document.
Also updated the existing commands to the latest WDL API and corrected the environment variable name for publishing crates.
Included the analysis rules in `sprocket explain`; the list of rules is now sorted by id.
> feat: add the `sprocket format` command.

- .github/pull_request_template.md
- .github/workflows/release.yml
- RELEASE.md
Also add the tag name to the published artifacts.
> chore: trigger release on `v*` tags.

- docs/vscode/getting-started.md
Includes information about the extension automatically installing `sprocket`.
> chore: update the extension documentation.

- CHANGELOG.md
- src/commands/format.rs
Requires that one of `--overwrite` or `--check` be provided and removes the default behavior of just printing the formatted files to stdout.
The `--overwrite` flag is now just a safety check so the caller knows that what they are doing is destructive, as writing the file is now "default" behavior, with `--check` being the modifier.
Test:
```
❯ cargo run --release format --check --overwrite ~/wdl/wdl-format/tests/format/optional_structs/
Finished `release` profile [optimized] target(s) in 0.07s
Running `target/release/sprocket format --check --overwrite /home/scott/wdl/wdl-format/tests/format/optional_structs/`
error: the argument '--check' cannot be used with '--overwrite'
Usage: sprocket format <--overwrite|--check> <PATH>
For more information, try '--help'.
```
```
❯ cargo run --release …
```
> feat: require one of check or overwrite options in format command

- README.md
The `validate-inputs` subcommand is missing from the README.
> Add `validate-inputs` to README

- CHANGELOG.md
- src/commands/check.rs
Fixes diagnostic counting that I messed up in #59 
Without this fix, "suppressed" Notes and Warnings will be counted and can lead to a confusing exit message.
> fix(check): correct diagnostic count

- CHANGELOG.md
- Cargo.lock
- src/commands/explain.rs
- `explain --help` now lists available tags along with available rules. (rules >>> tag)
- add `-t TAG` flag to list all rules which uses that `TAG` in alphabetical order
- add `--definitions` to show WDL definitions in markdown format
- `explain [RULE]` now shows related lint rules
Closes: #80 
Maybe tags should be listed above rules ?
> feat: extend explain command

- .github/workflows/release.yml
continue on publish error.
Using `|| true` feels a bit hacky here, but there aren't great alternatives in the GH workflow syntax. We could alternatively use `if: always()` or similar in subsequent steps, but this seems mildly preferable.
Also of note, there's no flag to `cargo publish` that can be used to achieve this, which seems like a missing feature if you ask me
GH refs:
- https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#status-check-functions
- https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsif
> fix: ignore failure to `publish` to crates.io

- Dockerfile
This commit adds the `openssl` package to the released Docker container. It also switches out the larger `debian:bookworm` image for the `debian:bookworm-slim`, which reduces the image by roughly 75MB.
> fix: adds `openssl` package to the Docker container

- .github/workflows/release.yml
This PR adds manifest merging across the multi-platform Docker builds (as described [here](https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners)) to fix the issue described in #97. You can see a successful build [here](https://github.com/claymcleod/sprocket/actions/runs/14450087515).
Closes #97.
> ci: fixes multi-platform Docker builds

- .github/workflows/stale.yml
There are a number of stale PRs. This copies the same logic we use in the `wdl` repo.
> ci: add stale PR closure

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/commands.rs
- src/commands/analyzer.rs
- src/commands/check.rs
- src/commands/explain.rs
- src/commands/format.rs
- src/commands/run.rs
- src/commands/validate.rs
- src/lib.rs
- src/main.rs
This commit is the second half of the changes needed to land incremental command line parsing into `sprocket`. The first half is at https://github.com/stjude-rust-labs/wdl/pull/430.
As indicated in the changes there, this commit also has the side effect of removing the `wdl` command line tool and putting all of the subcommands in `sprocket` instead. As such, you'll see many commands be modified to use the code created in the new `wdl-cli` package _OR_ brand new subcommands (like `run`).
> feat: introduces incremental command line parsing

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/commands/check.rs
This commit both updates `wdl` to v0.13.2 (fixes parsing of input files) _and_ removes the unused `--shellcheck` option.
> fix: removes unused `--shellcheck` option and updates `wdl` to v0.13.2

- CHANGELOG.md
- src/commands/check.rs
- src/commands/run.rs
This commit fixes a failure to print diagnostics after the analysis performed by `sprocket run`.
If the diagnostics contain any errors, the command aborts before evaluation is attempted.
Fixes #108.
Fixes #109.
> fix: print diagnostics for `sprocket run`.

- CHANGELOG.md
- Dockerfile
closes #112 
```sh
➜  sprocket git:(shellcheck) ✗ docker build -t sprocket .
[+] Building 435.2s (14/14) FINISHED                                                                                                           docker:default
=> [internal] load build definition from Dockerfile                                                                                                     0.1s
=> => transferring dockerfile: 447B                                                                                                                     0.0s
=> [internal] load metadata for docker.io/library/debian:bookworm-slim                                                                                  3.2s …
```
> feat: add shellcheck to dockerfile

- CHANGELOG.md
- src/commands/run.rs
- src/config.rs
Currently we flatten the engine configuration into the `run` configuration as `Option`. This has the unintended consequence of turning errors in deserializing a field within the engine configuration into a `None` for the entire engine configuration.
The result is implicitly using a default engine configuration when an engine configuration field fails to deserialize due to a call to `unwrap_or_default`.
The fix is to not make `engine` in the run configuration `Option`.
> fix: do not flatten engine configuration as optional.

- .github/workflows/CI.yml
- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
I initially noticed the `Cargo.lock` file is out of date on `main`, and in trying to address that realized that we inadvertently grew a diamond dependency problem around `indicatif` following a release of `tracing-indicatif`. This PR fixes that immediate issue, and also adds CI enforcement for the lockfile so that such problems will be caught earlier.
> chore: update `indicatif`, Cargo.lock, and enforce lockfile in CI

- Dockerfile
This approach will not be subject to breakage if/when the `sprocket` crate develops additional dependencies on files outside of what we manually specify in the Dockerfile, but uses a `mount` directive to avoid the potential for unnecessary copying into the builder image.
> chore: use `cargo install` and readonly mount for Docker build

- .gitignore
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/commands/check.rs
- src/commands/format.rs
- src/commands/run.rs
- src/commands/validate.rs
- src/config.rs
- tests/cli/run/help/stdout
In short, the default run directories are now located at `./runs/<entrypoint>/<timestamp>/`.
Also we have a `latest` symlink now 😎 
> feat: new and improved output dir logic

- crates/wdl-engine/CHANGELOG.md
- crates/wdl-engine/src/http.rs
Currently the file transferer uses the system tmp directory for linking files in the download cache to a location that can be used by Sprocket.
On many systems, though, the location is likely to be a different file system than where `sprocket` is configured to store its download cache; this prevents hardlinks and forces a fallback to a copy.
This fixes the transferer such that it uses a tmp directory within the cache root to maximum the success of creating a hardlink to the cache file.
For PRs containing lint rule changes:
possible diagnostic emitted for the rule within the file where the rule
is implemented.
> fix: use a `tmp` location to allow for hardlinking.
