CHANGELOG.md
src/commands/lint.rs
src/file.rs

fix: exit with 2 if lint warnings detected

---

CHANGELOG.md
Cargo.toml
src/commands/check.rs
src/commands/explain.rs
src/file.rs

Upgrade to latest `wdl`. Adds support for lint directives in code (`#@` comments) and also adds `--except` arg to `check --lint`/`lint` subcommands.

feat: upgrade to latest wdl. Add exceptions

---

Cargo.toml
src/file.rs

chore: bump `wdl` dependency version

---

.github/workflows/CI.yml
.github/workflows/docs.yml

This PR introduces GitHub pages deployment.

ci: introduces GitHub pages deployment

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/commands/analyzer.rs

chore: bump `wdl` dependency

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
docs/.vitepress/config.mts

chore: bump sprocket to `0.8.0`.

---

.github/workflows/release.yml

chore: disable fail fast on release artifacts.

---

.github/workflows/release.yml

chore: fix linux arm64 build artifact publishing.

---

.github/workflows/release.yml
Cargo.toml

chore: attempt to fix arm64 linux build and non-Windows packaging.

---

.github/workflows/release.yml

This PR produces a Windows ARM64 build of Sprocket as an artifact.

chore: produce an Windows ARM64 build of Sprocket.

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Also updates crate dependencies to latest.

release: bump sprocket to 0.9.0.

---

Cargo.lock

chore: update `Cargo.lock`.

---

src/commands/check.rs

Clarifies usage of the `--except` arg to `check/lint`.

docs: clarify use of --except

---

.github/workflows/CI.yml

ci: adds Windows CI

---

CHANGELOG.md
Cargo.lock
Cargo.toml
docs/.vitepress/config.mts

release: bumps version

---

.github/workflows/release.yml
CHANGELOG.md
Dockerfile
README.md

Adds a Dockerfile and release automation to address #43.

feat: Docker container

---

src/commands/check.rs
src/lib.rs

Addresses #54 and also surfaces diagnostics with `Severity::Error` regardless of CL options that would otherwise suppress the diagnostic.

feat(check): improvements to default behavior

---

RELEASE.md

Updates for current release process.

docs: update RELEASE.md

---

.github/workflows/release.yml

This PR adds ARM builds to the Docker image builder.

ci: adds ARM build to Docker image builder

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
src/commands/check.rs
src/commands/validate.rs
src/main.rs

feat: yaml support for `validate-inputs`

---

CHANGELOG.md
src/commands/check.rs

feat: Add `hide-notes` to hide note diagnostics from reporting

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
docs/.vitepress/config.mts
src/commands/check.rs
src/commands/explain.rs
src/commands/validate.rs
src/main.rs

release: bump versions

---

.github/workflows/release.yml

revise: version check before cargo publish

---

Dockerfile

fixes the docker image to allow URLs

fix: add ca-certificates to Dockerfile

---

.github/workflows/release.yml

This commit fixes the cross-platform asset building issues we've encountered in the CI.
I split each of the asset building platforms out into their own jobs, simply because it was getting too complicated with all of the `if` statements in the matrix calculation. Now, each step is a bit more straightforward as to the steps specifically for the platform at hand.
[This release](https://github.com/claymcleod/sprocket/actions/runs/14366794557) shows everything working now.

ci: fixes cross-platform asset building

---

.github/pull_request_template.md
README.md

This adds to the Contributing section of the README which is currently pretty terse. It is still terse, but points to the `wdl` repo for more information.

docs: reference the contributor guide in the `wdl` repo

---

CHANGELOG.md
src/commands/check.rs

feat: warn users about unknown --except rule

---

Cargo.toml

This commit contains small cleanups to the `Cargo.toml` file for Sprocket.

revise: small cleanups to the `Cargo.toml`

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
docs/installation.md
src/commands.rs
src/commands/check.rs
src/commands/completions.rs
src/commands/explain.rs
src/main.rs

feat: add support for tab completions

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
docs/.vitepress/config.mts
docs/cli/config.md
src/commands.rs
src/commands/check.rs
src/commands/config.rs
src/commands/format.rs
src/commands/run.rs
src/commands/validate.rs
src/config.rs
src/lib.rs
src/main.rs

This adds support for reading configuration files containing options specified by the user.

feat: configuration file support

---

README.md
docs/installation.md

This PR updates the documentation to outline how to install Sprocket with Homebrew. I also moved around some of the other sections to make the flow more logical given this change, and I changed the titles to sentence case.

docs: adds Homebrew installation

---

CHANGELOG.md
src/commands/run.rs
src/commands/validate.rs

fix: show some info if `validate` fails due to inputs supplied

---

README.md

This PR adds information about installing Sprocket from the GitHub releases page and expands information on how to install Sprocket with `cargo`.

chore: Update installation instructions in the README.

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
docs/.vitepress/config.mts
docs/installation.md
src/commands/check.rs
src/commands/doc.rs
src/commands/format.rs
src/commands/inputs.rs
src/commands/lock.rs
src/commands/run.rs
src/commands/validate.rs
tests/cli/explain/help/stdout
tests/cli/format/check/format_check_does_not_overwrite_file/stdout
tests/cli/format/overwrite/can_format_file_in_place/stdout
tests/cli/inputs/help/stdout

release: bump version

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
docs/.vitepress/config.mts
docs/installation.md

Fixes relative input files to `run` command.

release: patch

---

CHANGELOG.md
src/commands/run.rs
tests/cli/run/help/stdout

fix: use correct output logic for `run`

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/commands/analyzer.rs
src/config.rs
src/main.rs

feat: analyzer config

---

Dockerfile

fix: update builder image

---

Dockerfile

This commit switches the Docker image built by the repo's `Dockerfile` to use `alpine:latest` as the base image.
To make this work, we have to statically link openssl.

chore: switch to using an Alpine base image.

---

Dockerfile

chore: add missing `shellcheck` in Docker image.

---

.github/pull_request_template.md
RELEASE.md

This PR adds a checklist item that includes a check for updating content on sprocket.bio.

chore: adds a sprocket.bio checklist item

---

Cargo.lock
Cargo.toml

chore: update `wdl` dependency.

---

CHANGELOG.md
Cargo.lock
Cargo.toml
tests/cli/run/compare-coerced/args
tests/cli/run/ensure-absolute-inputs/args

release: bump version to `0.17.1`.

---

README.md

felt lost when updating my fork locally then realized crankshaft is now a submodule

chore: repo setup instructions

---

crates/wdl-analysis/CHANGELOG.md
crates/wdl-analysis/src/handlers/completions.rs
crates/wdl-analysis/src/stdlib.rs

part of https://github.com/stjude-rust-labs/sprocket-vscode/issues/39 (1/2)

feat: auto complete stdlib functions with snippets
